package com.kts.Restaurant.repository;

import org.neo4j.graphdb.Entity;

import org.springframework.data.neo4j.repository.Neo4jRepository;
import org.springframework.data.neo4j.repository.query.Query;
import org.springframework.stereotype.Repository;

import com.kts.Restaurant.model.GenericNode;


@Repository
public interface DBTestRepository  extends Neo4jRepository<GenericNode, Long> {
	
	@Query("CREATE (r1:Role {role : \"ADMIN\"})\r\n"
			+ "CREATE (r2:Role {role : \"MANAGER\"})\r\n"
			+ "CREATE (r3:Role {role : \"WAITER\"})\r\n"
			+ "CREATE (r4:Role {role : \"BARTENDER\"})\r\n"
			+ "CREATE (r5:Role {role : \"COOK\"})\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE (sa1:Salary {salaryAmount : 15000.0,  since : date('2020-08-21'), to : date('2020-09-21'), active : False})\r\n"
			+ "CREATE (sa2:Salary {salaryAmount : 20000.0,  since : date('2020-09-21'), to : date('2020-10-21'), active : False})\r\n"
			+ "CREATE (sa3:Salary {salaryAmount : 45000.0,  since : date('2020-10-21'), active : True})\r\n"
			+ "\r\n"
			+ "CREATE (sa4:Salary {salaryAmount : 54158.0,  since : date('2021-01-01'), to : date('2021-03-01'), active : False})\r\n"
			+ "CREATE (sa5:Salary {salaryAmount : 68989.0,  since : date('2021-03-01'), to : date('2021-05-01'), active : False})\r\n"
			+ "CREATE (sa6:Salary {salaryAmount : 70000.0,  since : date('2021-05-01'), active : True})\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE (u1:User {firstname : \"Marko\", lastname: \"Kopanja\", active : True})\r\n"
			+ "CREATE (u2:User {firstname : \"Marko\", lastname: \"Suhanov\", active : True})\r\n"
			+ "CREATE (u3:User {firstname : \"Nikola\", lastname: \"Nikolic\", active : True})\r\n"
			+ "CREATE (u4:User {firstname : \"Petar\", lastname: \"Petrovic\", active : True})\r\n"
			+ "CREATE (u5:User {firstname : \"Nemanja\", lastname: \"Nemanjic\", active : True})\r\n"
			+ "CREATE (u6:User {firstname : \"Jelena\", lastname: \"Lakic\", active : True})\r\n"
			+ "CREATE (u7:User {firstname : \"Luka\", lastname: \"Banjac\", active : True})\r\n"
			+ "CREATE (u8:User {firstname : \"Cezar\", lastname: \"Kopanja\", active : True})\r\n"
			+ "CREATE (u9:User {firstname : \"Stefan\", lastname: \"Nestorovic\", active : True})\r\n"
			+ "CREATE (u10:User {firstname : \"Jelena\", lastname: \"Tucic\", active : True})\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE (cred1:Credentials:UsernamePasswordCredentials {username : \"admin@gmail.com\", password : \"$2a$10$BYKqLdN2Usano9D9C4WixeAw4BokbB9h6VjyWHl.yG5LAVIVkYwCi\"})\r\n"
			+ "CREATE (cred2:Credentials:UsernamePasswordCredentials {username : \"menager@gmail.com\", password : \"$2a$10$84kxTedzkTde.DzZRtztR.JTxi73OIqAKDV1LOj.Y0DSTqHlDrPOm\"})\r\n"
			+ "CREATE (cred3:Credentials:PinCredentials {pin : \"$2a$10$Sn.Yhbpn.ghHu0O0.molAeWuwbcP/bV2ZV0a5oTs14La9CZ4CoFQC\"})\r\n"
			+ "CREATE (cred4:Credentials:PinCredentials {pin : \"$2a$10$WxmaVS/28KT3h1nb9Wa1ZuM0k2DZGz6mlt11jzM5zJA03PtOIWTLC\"})\r\n"
			+ "CREATE (cred5:Credentials:PinCredentials {pin : \"$2a$10$Iqsw0t6l2luCe3h/NUJKS.8bxZygpPy.SUO/HdX0kj/ga3eT0MBLy\"})\r\n"
			+ "CREATE (cred6:Credentials:PinCredentials {pin : \"4444\"})\r\n"
			+ "CREATE (cred7:Credentials:PinCredentials {pin : \"5555\"})\r\n"
			+ "CREATE (cred8:Credentials:PinCredentials {pin : \"6666\"})\r\n"
			+ "CREATE (cred9:Credentials:PinCredentials {pin : \"7777\"})\r\n"
			+ "CREATE (cred10:Credentials:PinCredentials {pin : \"8888\"})\r\n"
			+ "\r\n"
			+ "CREATE (tl:TableType {icon : \"tableLarge.png\", name : \"6seat\", numOfSeats : 6})\r\n"
			+ "CREATE (tm:TableType {icon : \"tableMedium.png\", name : \"4seat\", numOfSeats : 4})\r\n"
			+ "CREATE (ts:TableType {icon : \"tableSmall.png\", name : \"2seat\", numOfSeats : 2})\r\n"
			+ "\r\n"
			+ "CREATE (cf1: ItemCategory {type : \"Food\", categoryName : \"Burger\", icon : \"burger.png\"})\r\n"
			+ "CREATE (cf2: ItemCategory {type : \"Food\", categoryName : \"Pizza\", icon : \"pizza.png\"})\r\n"
			+ "CREATE (cf3: ItemCategory {type : \"Food\", categoryName : \"Salad\", icon : \"salad.png\"})\r\n"
			+ "CREATE (cf4: ItemCategory {type : \"Food\", categoryName : \"Dessert\", icon : \"dessert.png\"})\r\n"
			+ "CREATE (cf5: ItemCategory {type : \"Food\", categoryName : \"Barbeque\", icon : \"barbeque.png\"})\r\n"
			+ "\r\n"
			+ "CREATE (cd1: ItemCategory {type : \"Drink\", categoryName : \"Cocktail\", icon : \"cocktail.png\"})\r\n"
			+ "CREATE (cd2: ItemCategory {type : \"Drink\", categoryName : \"Coffe\", icon : \"coffe.png\"})\r\n"
			+ "CREATE (cd3: ItemCategory {type : \"Drink\", categoryName : \"Beer\", icon : \"beer.png\"})\r\n"
			+ "CREATE (cd4: ItemCategory {type : \"Drink\", categoryName : \"Wine\", icon : \"wine.png\"})\r\n"
			+ "CREATE (cd5: ItemCategory {type : \"Drink\", categoryName : \"Liquor\", icon : \"liquor.png\"})\r\n"
			+ "CREATE (cd6: ItemCategory {type : \"Drink\", categoryName : \"Soft Drinks\", icon : \"soft-drink.png\"})\r\n"
			+ "\r\n"
			+ "CREATE(b1:Item:FoodItem {cost : 234, description : \"description\", name : \"Classic Burger\", price : 650, active : True})\r\n"
			+ "CREATE(b2:Item:FoodItem {cost : 275, description : \"description\", name : \"Chesse Burger\", price : 690, active : True})\r\n"
			+ "CREATE(b3:Item:FoodItem {cost : 269, description : \"description\", name : \"Spicy Burger\", price : 700, active : True})\r\n"
			+ "CREATE(b4:Item:FoodItem {cost : 201, description : \"description\", name : \"Vege Burger\", price : 750, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(b5:Item:FoodItem {cost : 234, description : \"description\", name : \"Burger1\", price : 650, active : True})\r\n"
			+ "CREATE(b6:Item:FoodItem {cost : 275, description : \"description\", name : \"Burger2\", price : 690, active : True})\r\n"
			+ "CREATE(b7:Item:FoodItem {cost : 269, description : \"description\", name : \"Burger3\", price : 700, active : True})\r\n"
			+ "CREATE(b8:Item:FoodItem {cost : 201, description : \"description\", name : \"Burger4\", price : 750, active : True})\r\n"
			+ "CREATE(b9:Item:FoodItem {cost : 234, description : \"description\", name : \"Burger5\", price : 650, active : True})\r\n"
			+ "CREATE(b10:Item:FoodItem {cost : 275, description : \"description\", name : \"Burger6\", price : 690, active : True})\r\n"
			+ "CREATE(b11:Item:FoodItem {cost : 269, description : \"description\", name : \"Burger7\", price : 700, active : True})\r\n"
			+ "CREATE(b12:Item:FoodItem {cost : 201, description : \"description\", name : \"Burger8\", price : 750, active : True})\r\n"
			+ "CREATE(b13:Item:FoodItem {cost : 234, description : \"description\", name : \"Burger9\", price : 650, active : True})\r\n"
			+ "CREATE(b14:Item:FoodItem {cost : 275, description : \"description\", name : \"Burger10\", price : 690, active : True})\r\n"
			+ "CREATE(b15:Item:FoodItem {cost : 269, description : \"description\", name : \"Burger11\", price : 700, active : True})\r\n"
			+ "CREATE(b16:Item:FoodItem {cost : 201, description : \"description\", name : \"Burger12\", price : 750, active : True})\r\n"
			+ "CREATE(b17:Item:FoodItem {cost : 234, description : \"description\", name : \"Burger13\", price : 650, active : True})\r\n"
			+ "CREATE(b18:Item:FoodItem {cost : 275, description : \"description\", name : \"Burger14\", price : 690, active : True})\r\n"
			+ "CREATE(b19:Item:FoodItem {cost : 269, description : \"description\", name : \"Burger15\", price : 700, active : True})\r\n"
			+ "CREATE(b20:Item:FoodItem {cost : 201, description : \"description\", name : \"Burger16\", price : 750, active : True})\r\n"
			+ "CREATE(b21:Item:FoodItem {cost : 201, description : \"description\", name : \"Burger17\", price : 750, active : True})\r\n"
			+ "CREATE(b22:Item:FoodItem {cost : 234, description : \"description\", name : \"Burger18\", price : 650, active : True})\r\n"
			+ "CREATE(b23:Item:FoodItem {cost : 275, description : \"description\", name : \"Burger19\", price : 690, active : True})\r\n"
			+ "CREATE(b24:Item:FoodItem {cost : 269, description : \"description\", name : \"Burger20\", price : 700, active : True})\r\n"
			+ "CREATE(b25:Item:FoodItem {cost : 201, description : \"description\", name : \"Burger21\", price : 750, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(p1:Item:FoodItem {cost : 345, description : \"description\", name : \"Capricciosa\", price : 950, active : True})\r\n"
			+ "CREATE(p2:Item:FoodItem {cost : 355, description : \"description\", name : \"4 Chesse Pizza\", price : 1050, active : True})\r\n"
			+ "CREATE(p3:Item:FoodItem {cost : 300, description : \"description\", name : \"Margarita\", price : 870, active : True})\r\n"
			+ "CREATE(p4:Item:FoodItem {cost : 270, description : \"description\", name : \"Vegetariana\", price : 1100, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(s1:Item:FoodItem {cost : 135, description : \"description\", name : \"Caesar Salad\", price : 450, active : True})\r\n"
			+ "CREATE(s2:Item:FoodItem {cost : 145, description : \"description\", name : \"Garden Salad\", price : 460, active : True})\r\n"
			+ "CREATE(s3:Item:FoodItem {cost : 120, description : \"description\", name : \"Egg Salad\", price : 430, active : True})\r\n"
			+ "CREATE(s4:Item:FoodItem {cost : 100, description : \"description\", name : \"Potato Salad\", price : 390, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(d1:Item:FoodItem {cost : 135, description : \"description\", name : \"Cheese Cake\", price : 450, active : True})\r\n"
			+ "CREATE(d2:Item:FoodItem {cost : 145, description : \"description\", name : \"Bannana Split\", price : 460, active : True})\r\n"
			+ "CREATE(d3:Item:FoodItem {cost : 120, description : \"description\", name : \"Chocolate Cake\", price : 430, active : True})\r\n"
			+ "CREATE(d4:Item:FoodItem {cost : 100, description : \"description\", name : \"Tiramisu\", price : 390, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(br1:Item:FoodItem {cost : 330, description : \"description\", name : \"Pulled Pork\", price : 1400, active : True})\r\n"
			+ "CREATE(br2:Item:FoodItem {cost : 540, description : \"description\", name : \"Tomahawk Steak\", price : 1600, active : True})\r\n"
			+ "CREATE(br3:Item:FoodItem {cost : 370, description : \"description\", name : \"Pineapple And Pork Skewers\", price : 1100, active : True})\r\n"
			+ "CREATE(br4:Item:FoodItem {cost : 330, description : \"description\", name : \"Piri Piri Chicken\", price : 1300, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(ck1:Item:DrinkItem {cost : 78, description : \"This is a drink\", name : \"Sex On The Beach\", price : 370, active : True})\r\n"
			+ "CREATE(ck2:Item:DrinkItem {cost : 59, description : \"This is a drink\", name : \"Tequila Sunrise\", price : 330, active : True})\r\n"
			+ "CREATE(ck3:Item:DrinkItem {cost : 60, description : \"This is a drink\", name : \"Mojito\", price : 310, active : True})\r\n"
			+ "CREATE(ck4:Item:DrinkItem {cost : 63, description : \"This is a drink\", name : \"Devils Ice Tea\", price : 390, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(co1:Item:DrinkItem {cost : 17, description : \"This is a drink\", name : \"Turkish Coffe\", price : 100, active : True})\r\n"
			+ "CREATE(co2:Item:DrinkItem {cost : 19, description : \"This is a drink\", name : \"Espresso\", price : 120, active : True})\r\n"
			+ "CREATE(co3:Item:DrinkItem {cost : 19, description : \"This is a drink\", name : \"Americano\", price : 130, active : True})\r\n"
			+ "CREATE(co4:Item:DrinkItem {cost : 21, description : \"This is a drink\", name : \"Latte\", price : 140, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(be1:Item:DrinkItem {cost : 69, description : \"This is a drink\", name : \"Tuborg\", price : 190, active : True})\r\n"
			+ "CREATE(be2:Item:DrinkItem {cost : 59, description : \"This is a drink\", name : \"Carlsberg\", price : 175, active : True})\r\n"
			+ "CREATE(be3:Item:DrinkItem {cost : 63, description : \"This is a drink\", name : \"Budweiser\", price : 179, active : True})\r\n"
			+ "CREATE(be4:Item:DrinkItem {cost : 71, description : \"This is a drink\", name : \"Heineken\", price : 210, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(w1:Item:DrinkItem {cost : 110, description : \"This is a drink\", name : \"Mouton Cadet\", price : 310, active : True})\r\n"
			+ "CREATE(w2:Item:DrinkItem {cost : 90, description : \"This is a drink\", name : \"Sierra Cantabria\", price : 290, active : True})\r\n"
			+ "CREATE(w3:Item:DrinkItem {cost : 89, description : \"This is a drink\", name : \"Masseto\", price : 290, active : True})\r\n"
			+ "CREATE(w4:Item:DrinkItem {cost : 94, description : \"This is a drink\", name : \"Giuseppe Quintarelli\", price : 300, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(l1:Item:DrinkItem {cost : 110, description : \"This is a drink\", name : \"Whiskey\", price : 310, active : True})\r\n"
			+ "CREATE(l2:Item:DrinkItem {cost : 90, description : \"This is a drink\", name : \"Tequila\", price : 290, active : True})\r\n"
			+ "CREATE(l3:Item:DrinkItem {cost : 89, description : \"This is a drink\", name : \"Vodka\", price : 290, active : True})\r\n"
			+ "CREATE(l4:Item:DrinkItem {cost : 94, description : \"This is a drink\", name : \"Absinth\", price : 300, active : True})\r\n"
			+ "\r\n"
			+ "CREATE(so1:Item:DrinkItem {cost : 43, description : \"This is a drink\", name : \"Sparkling Water\", price : 169, active : True})\r\n"
			+ "CREATE(so2:Item:DrinkItem {cost : 33, description : \"This is a drink\", name : \"Mineral Water\", price : 149, active : True})\r\n"
			+ "CREATE(so3:Item:DrinkItem {cost : 41, description : \"This is a drink\", name : \"Coca Cola\", price : 169, active : True})\r\n"
			+ "CREATE(so4:Item:DrinkItem {cost : 41, description : \"This is a drink\", name : \"Sprite\", price : 159, active : True})\r\n"
			+ "CREATE(so5:Item:DrinkItem {cost : 33, description : \"This is a drink\", name : \"Orange Juice\", price : 140, active : True})\r\n"
			+ "CREATE(so6:Item:DrinkItem {cost : 33, description : \"This is a drink\", name : \"Apple Juice\", price : 140, active : True})\r\n"
			+ "CREATE(so7:Item:DrinkItem {cost : 42, description : \"This is a drink\", name : \"Tonic\", price : 169, active : True})\r\n"
			+ "CREATE(so8:Item:DrinkItem {cost : 33, description : \"This is a drink\", name : \"Lemonade\", price : 140, active : True})\r\n"
			+ "	\r\n"
			+ "CREATE (f1:Floor {name: \"Floor1\"})\r\n"
			+ "CREATE (f2:Floor {name: \"Floor2\"})\r\n"
			+ "		\r\n"
			+ "CREATE (ts1:Table {x : 175, y : 170, name: \"Table1\"})\r\n"
			+ "CREATE (ts2:Table {x : 421, y : 143, name: \"Table2\"})\r\n"
			+ "CREATE (ts3:Table {x : 174, y : 354, name: \"Table3\"})\r\n"
			+ "CREATE (ts4:Table {x : 0, y : 203, name: \"Table9\"})\r\n"
			+ "CREATE (ts5:Table {x : 175, y : 203, name: \"Table10\"})\r\n"
			+ "		\r\n"
			+ "CREATE (tm1:Table {x : 178, y : 11, name: \"Table4\"})\r\n"
			+ "CREATE (tm2:Table {x : 421, y : 1, name: \"Table5\"})\r\n"
			+ "CREATE (tm3:Table {x : 421, y : 1, name: \"Table11\"})\r\n"
			+ "		\r\n"
			+ "CREATE (tl1:Table {x : 0, y : 203, name: \"Table6\"})\r\n"
			+ "CREATE (tl2:Table {x : 0, y : 19, name: \"Table7\"})\r\n"
			+ "CREATE (tl3:Table {x : 421, y : 327, name: \"Table8\"})\r\n"
			+ "CREATE (tl4:Table {x : 421, y : 327, name: \"Table12\"})\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE(o:Order)\r\n"
			+ "CREATE (oi1:OrderedItem {prepared : false})\r\n"
			+ "CREATE (oi2:OrderedItem {prepared : false})\r\n"
			+ "CREATE (oi3:OrderedItem {prepared : false})\r\n"
			+ "CREATE (oi4:OrderedItem {prepared : false})\r\n"
			+ "\r\n"
			+ "CREATE(o2:Order)\r\n"
			+ "CREATE (oi5:OrderedItem {prepared : false})\r\n"
			+ "\r\n"
			+ "CREATE(o3:Order)\r\n"
			+ "CREATE (oi6:OrderedItem {prepared : false})\r\n"
			+ "\r\n"
			+ "CREATE (bo:Bill {price : 1450, cost : 519, date : date('2021-12-21')})\r\n"
			+ "CREATE (bi1:BilledItem)\r\n"
			+ "CREATE (bi2:BilledItem)\r\n"
			+ "CREATE (bi3:BilledItem)\r\n"
			+ "\r\n"
			+ "MERGE (bo)-[:HAD_WAITER]->(u3)\r\n"
			+ "MERGE (bo)-[:BILLED_ITEM]->(bi1)-[:IS_ITEM]->(l1)\r\n"
			+ "MERGE (bo)-[:BILLED_ITEM]->(bi2)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo)-[:BILLED_ITEM]->(bi3)-[:IS_ITEM]->(p1)\r\n"
			+ "\r\n"
			+ "CREATE (bo1:Bill {price : 1140, cost : 414, date : date('2021-12-24')})\r\n"
			+ "CREATE (bi4:BilledItem)\r\n"
			+ "CREATE (bi5:BilledItem)\r\n"
			+ "CREATE (bi6:BilledItem)\r\n"
			+ "CREATE (bi7:BilledItem)\r\n"
			+ "CREATE (bi8:BilledItem)\r\n"
			+ "CREATE (bi9:BilledItem)\r\n"
			+ "\r\n"
			+ "MERGE (bo1)-[:HAD_WAITER]->(u3)\r\n"
			+ "MERGE (bo1)-[:BILLED_ITEM]->(bi4)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo1)-[:BILLED_ITEM]->(bi5)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo1)-[:BILLED_ITEM]->(bi6)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo1)-[:BILLED_ITEM]->(bi7)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo1)-[:BILLED_ITEM]->(bi8)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo1)-[:BILLED_ITEM]->(bi9)-[:IS_ITEM]->(be1)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE (bo3:Bill {price : 2260, cost : 808, date : date('2021-12-27')})\r\n"
			+ "CREATE (bi10:BilledItem)\r\n"
			+ "CREATE (bi11:BilledItem)\r\n"
			+ "CREATE (bi12:BilledItem)\r\n"
			+ "CREATE (bi13:BilledItem)\r\n"
			+ "CREATE (bi14:BilledItem)\r\n"
			+ "CREATE (bi15:BilledItem)\r\n"
			+ "\r\n"
			+ "MERGE (bo3)-[:HAD_WAITER]->(u3)\r\n"
			+ "MERGE (bo3)-[:BILLED_ITEM]->(bi10)-[:IS_ITEM]->(p1)\r\n"
			+ "MERGE (bo3)-[:BILLED_ITEM]->(bi11)-[:IS_ITEM]->(l1)\r\n"
			+ "MERGE (bo3)-[:BILLED_ITEM]->(bi12)-[:IS_ITEM]->(l1)\r\n"
			+ "MERGE (bo3)-[:BILLED_ITEM]->(bi13)-[:IS_ITEM]->(w1)\r\n"
			+ "MERGE (bo3)-[:BILLED_ITEM]->(bi14)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo3)-[:BILLED_ITEM]->(bi15)-[:IS_ITEM]->(be1)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE (bo4:Bill {price : 2527, cost : 895, date : date('2022-01-11')})\r\n"
			+ "CREATE (bi17:BilledItem)\r\n"
			+ "CREATE (bi18:BilledItem)\r\n"
			+ "CREATE (bi19:BilledItem)\r\n"
			+ "CREATE (bi20:BilledItem)\r\n"
			+ "CREATE (bi21:BilledItem)\r\n"
			+ "CREATE (bi22:BilledItem)\r\n"
			+ "\r\n"
			+ "MERGE (bo4)-[:HAD_WAITER]->(u4)\r\n"
			+ "MERGE (bo4)-[:BILLED_ITEM]->(bi17)-[:IS_ITEM]->(b1)\r\n"
			+ "MERGE (bo4)-[:BILLED_ITEM]->(bi18)-[:IS_ITEM]->(b2)\r\n"
			+ "MERGE (bo4)-[:BILLED_ITEM]->(bi19)-[:IS_ITEM]->(b3)\r\n"
			+ "MERGE (bo4)-[:BILLED_ITEM]->(bi20)-[:IS_ITEM]->(so1)\r\n"
			+ "MERGE (bo4)-[:BILLED_ITEM]->(bi21)-[:IS_ITEM]->(so2)\r\n"
			+ "MERGE (bo4)-[:BILLED_ITEM]->(bi22)-[:IS_ITEM]->(so3)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "CREATE (bo5:Bill {price : 2520, cost : 909, date : date('2022-01-15')})\r\n"
			+ "CREATE (bi23:BilledItem)\r\n"
			+ "CREATE (bi24:BilledItem)\r\n"
			+ "CREATE (bi25:BilledItem)\r\n"
			+ "CREATE (bi26:BilledItem)\r\n"
			+ "CREATE (bi27:BilledItem)\r\n"
			+ "CREATE (bi28:BilledItem)\r\n"
			+ "\r\n"
			+ "MERGE (bo5)-[:HAD_WAITER]->(u5)\r\n"
			+ "MERGE (bo5)-[:BILLED_ITEM]->(bi23)-[:IS_ITEM]->(b1)\r\n"
			+ "MERGE (bo5)-[:BILLED_ITEM]->(bi24)-[:IS_ITEM]->(b1)\r\n"
			+ "MERGE (bo5)-[:BILLED_ITEM]->(bi25)-[:IS_ITEM]->(b1)\r\n"
			+ "MERGE (bo5)-[:BILLED_ITEM]->(bi26)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo5)-[:BILLED_ITEM]->(bi27)-[:IS_ITEM]->(be1)\r\n"
			+ "MERGE (bo5)-[:BILLED_ITEM]->(bi28)-[:IS_ITEM]->(be1)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "MERGE(u1)-[:HAS_ROLE]->(r1)\r\n"
			+ "MERGE(u2)-[:HAS_ROLE]->(r2)\r\n"
			+ "MERGE(u3)-[:HAS_ROLE]->(r3)\r\n"
			+ "MERGE(u4)-[:HAS_ROLE]->(r3)\r\n"
			+ "MERGE(u5)-[:HAS_ROLE]->(r3)\r\n"
			+ "MERGE(u6)-[:HAS_ROLE]->(r3)\r\n"
			+ "MERGE(u7)-[:HAS_ROLE]->(r4)\r\n"
			+ "MERGE(u8)-[:HAS_ROLE]->(r4)\r\n"
			+ "MERGE(u9)-[:HAS_ROLE]->(r5)\r\n"
			+ "MERGE(u10)-[:HAS_ROLE]->(r5)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "MERGE(u1)-[:HAS_CREDENTIALS]->(cred1)\r\n"
			+ "MERGE(u2)-[:HAS_CREDENTIALS]->(cred2)\r\n"
			+ "MERGE(u3)-[:HAS_CREDENTIALS]->(cred3)\r\n"
			+ "MERGE(u7)-[:HAS_CREDENTIALS]->(cred4)\r\n"
			+ "MERGE(u9)-[:HAS_CREDENTIALS]->(cred5)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "MERGE(u3)-[:HAS_SALARY]->(sa1)\r\n"
			+ "MERGE(u3)-[:HAS_SALARY]->(sa2)\r\n"
			+ "MERGE(u3)-[:HAS_SALARY]->(sa3)\r\n"
			+ "\r\n"
			+ "MERGE(u4)-[:HAS_SALARY]->(sa4)\r\n"
			+ "MERGE(u4)-[:HAS_SALARY]->(sa5)\r\n"
			+ "MERGE(u4)-[:HAS_SALARY]->(sa6)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "MERGE(b1)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b2)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b3)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b4)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b5)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b6)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b7)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b8)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b9)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b10)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b11)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b12)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b13)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b14)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b15)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b16)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b17)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b18)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b19)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b20)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b21)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b22)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b23)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b24)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "MERGE(b25)-[:HAS_CATEGORY]->(cf1)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "MERGE(p1)-[:HAS_CATEGORY]->(cf2)\r\n"
			+ "MERGE(p2)-[:HAS_CATEGORY]->(cf2)\r\n"
			+ "MERGE(p3)-[:HAS_CATEGORY]->(cf2)\r\n"
			+ "MERGE(p4)-[:HAS_CATEGORY]->(cf2)\r\n"
			+ "\r\n"
			+ "MERGE(s1)-[:HAS_CATEGORY]->(cf3)\r\n"
			+ "MERGE(s2)-[:HAS_CATEGORY]->(cf3)\r\n"
			+ "MERGE(s3)-[:HAS_CATEGORY]->(cf3)\r\n"
			+ "MERGE(s4)-[:HAS_CATEGORY]->(cf3)\r\n"
			+ "\r\n"
			+ "MERGE(d1)-[:HAS_CATEGORY]->(cf4)\r\n"
			+ "MERGE(d2)-[:HAS_CATEGORY]->(cf4)\r\n"
			+ "MERGE(d3)-[:HAS_CATEGORY]->(cf4)\r\n"
			+ "MERGE(d4)-[:HAS_CATEGORY]->(cf4)\r\n"
			+ "\r\n"
			+ "MERGE(br1)-[:HAS_CATEGORY]->(cf5)\r\n"
			+ "MERGE(br2)-[:HAS_CATEGORY]->(cf5)\r\n"
			+ "MERGE(br3)-[:HAS_CATEGORY]->(cf5)\r\n"
			+ "MERGE(br4)-[:HAS_CATEGORY]->(cf5)\r\n"
			+ "\r\n"
			+ "MERGE(ck1)-[:HAS_CATEGORY]->(cd1)\r\n"
			+ "MERGE(ck2)-[:HAS_CATEGORY]->(cd1)\r\n"
			+ "MERGE(ck3)-[:HAS_CATEGORY]->(cd1)\r\n"
			+ "MERGE(ck4)-[:HAS_CATEGORY]->(cd1)\r\n"
			+ "\r\n"
			+ "MERGE(co1)-[:HAS_CATEGORY]->(cd2)\r\n"
			+ "MERGE(co2)-[:HAS_CATEGORY]->(cd2)\r\n"
			+ "MERGE(co3)-[:HAS_CATEGORY]->(cd2)\r\n"
			+ "MERGE(co4)-[:HAS_CATEGORY]->(cd2)\r\n"
			+ "\r\n"
			+ "MERGE(be1)-[:HAS_CATEGORY]->(cd3)\r\n"
			+ "MERGE(be2)-[:HAS_CATEGORY]->(cd3)\r\n"
			+ "MERGE(be3)-[:HAS_CATEGORY]->(cd3)\r\n"
			+ "MERGE(be4)-[:HAS_CATEGORY]->(cd3)\r\n"
			+ "\r\n"
			+ "MERGE(w1)-[:HAS_CATEGORY]->(cd4)\r\n"
			+ "MERGE(w2)-[:HAS_CATEGORY]->(cd4)\r\n"
			+ "MERGE(w3)-[:HAS_CATEGORY]->(cd4)\r\n"
			+ "MERGE(w4)-[:HAS_CATEGORY]->(cd4)\r\n"
			+ "\r\n"
			+ "MERGE(l1)-[:HAS_CATEGORY]->(cd5)\r\n"
			+ "MERGE(l2)-[:HAS_CATEGORY]->(cd5)\r\n"
			+ "MERGE(l3)-[:HAS_CATEGORY]->(cd5)\r\n"
			+ "MERGE(l4)-[:HAS_CATEGORY]->(cd5)\r\n"
			+ "\r\n"
			+ "MERGE(so1)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so2)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so3)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so4)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so5)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so6)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so7)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "MERGE(so8)-[:HAS_CATEGORY]->(cd6)\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "MERGE (oi1)-[:IS_ITEM]->(w1)\r\n"
			+ "MERGE (oi2)-[:IS_ITEM]->(co1)\r\n"
			+ "MERGE (oi3)-[:IS_ITEM]->(br1)\r\n"
			+ "MERGE (oi4)-[:IS_ITEM]->(b3)\r\n"
			+ "\r\n"
			+ "MERGE (oi5)-[:IS_ITEM]->(d2)\r\n"
			+ "MERGE (oi6)-[:IS_ITEM]->(co2)\r\n"
			+ "\r\n"
			+ "MERGE (o)-[:HAS]->(oi1)\r\n"
			+ "MERGE (o)-[:HAS]->(oi2)\r\n"
			+ "MERGE (o)-[:HAS]->(oi3)\r\n"
			+ "MERGE (o)-[:HAS]->(oi4)\r\n"
			+ "\r\n"
			+ "MERGE (o2)-[:HAS]->(oi5)\r\n"
			+ "MERGE (o3)-[:HAS]->(oi6)\r\n"
			+ "\r\n"
			+ "MERGE (ts1)-[:HAS_ORDER]->(o)\r\n"
			+ "MERGE (tm1)-[:HAS_ORDER]->(o2)\r\n"
			+ "MERGE (tm2)-[:HAS_ORDER]->(o3)\r\n"
			+ "\r\n"
			+ "MERGE (ts1)-[:IS_TYPE]->(ts)\r\n"
			+ "MERGE (ts2)-[:IS_TYPE]->(ts)\r\n"
			+ "MERGE (ts3)-[:IS_TYPE]->(ts)\r\n"
			+ "MERGE (ts4)-[:IS_TYPE]->(ts)\r\n"
			+ "MERGE (ts5)-[:IS_TYPE]->(ts)\r\n"
			+ "	\r\n"
			+ "MERGE (tm1)-[:IS_TYPE]->(tm)\r\n"
			+ "MERGE (tm2)-[:IS_TYPE]->(tm)\r\n"
			+ "MERGE (tm3)-[:IS_TYPE]->(tm)\r\n"
			+ "		\r\n"
			+ "MERGE (tl1)-[:IS_TYPE]->(tl)\r\n"
			+ "MERGE (tl2)-[:IS_TYPE]->(tl)\r\n"
			+ "MERGE (tl3)-[:IS_TYPE]->(tl)\r\n"
			+ "MERGE (tl4)-[:IS_TYPE]->(tl)\r\n"
			+ "\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(ts1)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(ts2)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(ts3)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(tm1)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(tm2)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(tl1)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(tl2)\r\n"
			+ "MERGE (f1)-[:HAS_TABLE]->(tl3)\r\n"
			+ "		\r\n"
			+ "MERGE (f2)-[:HAS_TABLE]->(ts4)\r\n"
			+ "MERGE (f2)-[:HAS_TABLE]->(ts5)\r\n"
			+ "MERGE (f2)-[:HAS_TABLE]->(tl4)\r\n"
			+ "MERGE (f2)-[:HAS_TABLE]->(tm3)")	
	public void createDBData();
	
	
	@Query("MATCH (n)\r\n"
			+ "DETACH DELETE n")
	public void deleteEveryNodeAndRel();

}
